Provide Flink-K8s Runtime Support for StreamX
streamxhub/streamx pull request #325
Opened 2021-09-27 11:21 UTC by wolfboys

Signed-off-by: Al-assad yulin.ying@outlook.com, wolfboys benjobs@qq.com
<br/>
### What problem does this PR solve?

Issue Number: 325

Problem Summary: Provide Flink-K8s Runtime Support for StreamX

### What is changed and how it works?
What's Changed:
* Support for submit/cancel Flink-SQL-Job on Flink-K8s-native session/application mode.
* Support for tracking Flink job status and metrics information from Flink-K8s cluster.
* Support for StreamX instance to manage both Flink-Yarn or Flink-K8s runtime Cluster, and to use either independently.

<br/>

2021-09-27 11:24 UTC, Al-assad commented
LGBT🌝

2021-09-28 09:29 UTC, Al-assad requested changes
我们需要要将 pom.xml 中的 streamx 版本更新到 1.2.0

2021-09-28 10:07 UTC, Al-assad reviewed
The main code is fine, but we need to update all the streamx-components in pom.xml to version 1.2.0 : )

2021-09-28 16:56 UTC, wolfboys commented on streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/StreamXConsole.java
> + *  │   Ver    :  1.1.2                                  │
done.

2021-09-28 16:56 UTC, wolfboys commented on streamx-console/streamx-console-service/src/main/resources/banner.txt
> +      │   Ver    :  1.1.2                                  │
done

2021-09-29 05:22 UTC, wolfboys commented on streamx-flink/streamx-flink-shims/streamx-flink-shims-base/src/main/scala/com/streamxhub/streamx/flink/core/SqlCommandParser.scala
> +        groups(i) = matcher.group(i + 1)
👌🏻放到下个版本,重新设计下sql部分.

2021-09-29 05:47 UTC, Al-assad approved these changes
LGTM

2021-09-29 05:54 UTC, wolfboys commented
LGTM

2021-09-29 05:55 UTC, merged